### ISSUE TITLE
fix skipped tests

### ISSUE THREAD

**Issue by noot** [ChainSafe/gossamer#1026]
## Expected Behavior

- tests should pass on CI if they pass locally
- add back skipped tests

## Current Behavior

some tests fail randomly on CI: (add more as needed)

- [ ] network `TestGossip`, `TestStreamManager_KeepStream`, `TestPersistentPeers`, `TestRemovePeer`, `TestSetReservedPeer`
- [ ] messages `TestService_HandleTransactionMessage`
- [ ] author `TestAuthorModule_SubmitExtrinsic`
- [ ] author `TestAuthorModule_SubmitExtrinsic_invalid`
- [ ] author `TestAuthorModule_SubmitExtrinsic_InQueue`
- [ ] rpc `TestStateModule_GetMetadata`
- [ ] build `TestBuildBlock_failing`
- [ ] extrinsics `TestAuthoritiesChangeExt_Encode`
- [ ] exports `TestInstance_ExecuteBlock_PolkadotRuntime_PolkadotBlock1`, `TestInstance_Version_NodeRuntime`
- [ ] imports `Test_ext_storage_clear_prefix_version_1`
- [ ] wasmer `TestInstance_ExecuteBlock_GossamerRuntime`, `TestInstance_ApplyExtrinsic_GossamerRuntime`, `Test_ext_offline_index_set_version_1`
- [ ] grandpa `TestGrandpa_NonAuthority`, `TestStress_Grandpa_ThreeAuthorities`, `TestStress_Grandpa_SixAuthorities`, `TestGrandpa_DifferentChains`
- [ ] stress tests `TestSync_SingleSyncingNode`, `TestSync_ManyProducers`, `TestSync_Restart`, `TestSync_MultipleEpoch`

## Possible Solution

- this may be due to some underlying randomness
- for integration tests, this is probably due to timing issues

## Checklist

- [x] I have read [CODE_OF_CONDUCT](https://github.com/ChainSafe/gossamer/blob/development/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING](https://github.com/ChainSafe/gossamer/blob/development/.github/CONTRIBUTING.md) 
- [x] I have provided as much information as possible and necessary
- [ ] I am planning to submit a pull request to fix this issue myself

**Comment by kishansagathiya** [comment]
Some more context on TestGossip here https://github.com/ChainSafe/gossamer/issues/1026

**Comment by kishansagathiya** [comment]
I have fixed some of the skipped tests (the ones related to dot/peerset and dot/network) in dht pr https://github.com/ChainSafe/gossamer/pull/2059

**Comment by jimjbrettj** [comment]
We have rewritten many tests in our package making this issue stale.
