### ISSUE TITLE
Implement Grandpa RPC calls and tests

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/gossamer#1372]
## Task summary

**Please submit implementation with corresponding test.**

Implement the following missing RPC calls:

### Grandpa RPC calls
- [x] [`proveFinality`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#172-grandpa_provefinality)
- [ ] [`roundState`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#171-grandpa_roundstate)
- [ ] [`subscribeJustifications`](https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#173-grandpa_subscribejustifications-pubsub)

## Specification reference

- https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md#17-grandpa

## Other information and links

-

**Comment by RyRy79261** [comment]
@dutterbutter Gonna make a ticket for `proveFinality` and work on that

**Comment by dutterbutter** [comment]
Closing in favour of #1396
