### ISSUE TITLE
Integrate scale package into internal packages

### ISSUE THREAD

**Issue by timwu20** [ChainSafe/gossamer#1621]
## Task summary

- Evaluate use of custom `Encode()`/`Decode()` functionality on struct types.  Should all be covered by new `Marshal()`/`Unmarshal()` functionality.  Remove the `Encode()`/`Decode()` receiver functions.
- Change all occurrences of `Encode()`/`Decode()` to use new `Marshal()`/`Unmarshal()` interface.
- Implement `VaryingDataType` pattern for existing structs that decode SCALE/Rust enums
- Implement `Result` pattern for existing use case in `lib/runtime/wasmer/imports.go`
- Ensure that existing encoded data stored in DB is successfully decoded

## Specification reference

-  https://github.com/w3f/polkadot-spec/releases/download/v0.1.0-beta1/polkadot-host-spec_v0.1.0-beta1.pdf

## Other information and links

- https://github.com/ChainSafe/gossamer/tree/tim/scale/pkg/scale
- https://github.com/paritytech/parity-scale-codec
- https://substrate.dev/docs/en/knowledgebase/advanced/codec

**Comment by jimjbrettj** [comment]
- [ ] lib/babe
- [ ] lib/common
- [ ] lib/genesis
- [ ] lib/grandpa
- [ ] lib/runtime
- [ ] lib/transaction
- [ ] lib/trie
- [ ] dot/core
- [ ] dot/digest WIP
- [ ] dot/network WIP
- [ ] dot/rpc
- [ ] dot/state
- [ ] dot/sync
- [ ] dot/types WIP

**Comment by noot** [comment]
closing as this has been completed
