### ISSUE TITLE
Fix DeepSource issues detected for Release V0.6.0

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#1729]
## Task summary

During merge of development into main for release v0.6.0, DeepSource analysis detected the following issues:
- [x] Unused code in dot/network/host.go starting at line 228
- [x] Return of `nil` value detected in lib/scale/encode.go at line 128
- [x] Shadow of builtin detected in dot/rpc/service.go at line 94
- [ ] Function call made to an unsafe package in dot/network/notifications.go at line 32
- [x] Audit the random number generation source (rand) in:
     - lib/trie/test_utils.go line 42
     - dot/state/test_helpers.go line 64
     - dot/network/utils.go line 71
     - dot/network/connmgr.go line 166
- [ ] Empty body in an if or else branch in dot/rpc/modules/grandpa.go line 80

## Specification reference

- see https://deepsource.io/gh/ChainSafe/gossamer/run/52c1d515-ffe8-4cf8-a9f0-324143e289cf/go/ for details.

## Other information and links

-
