### ISSUE TITLE
lib/trie: refactor and add tests for trie and database related code

### ISSUE THREAD

**Issue by qdm12** [ChainSafe/gossamer#2085]
## Task summary

- [x] Database code fully tested; then
- [x] Database code refactored
- [x] Trie code (lib/trie/trie.go) fully tested
- [ ] Trie code refactored
