### ISSUE TITLE
lib(wasmer): Upgade wasmer to newest version

### ISSUE THREAD

**Issue by jimjbrettj** [ChainSafe/gossamer#3136]
## Issue summary

- Current version of wasmer is causing issues in our tests, specifically in TestVerifyAuthorshipRight_Equivocation in babe/verify_integration_test.go. Future issues could also arise from using the outdated version
- Could also be reason to investigate using wazero instead of wasmer
- See relevant links for more context

List of tasks for this epic:
- [x] #3157 
- [x] Remove usage of wasmer.InstanceContext as it is no longer supported
- [x] Create an imports_func file to create a *wasm.ImportObject (this will replace the current ImportsNodeRuntime() function)
- [x] Rewrite Instance.go to use current wasmer version
- [x] Refactor imports and exports go files to use new instance 

## Other information and links

- https://github.com/wasmerio/wasmer-go/issues/93
- https://github.com/ChainSafe/gossamer/pull/1484
- https://github.com/CosmWasm/cosmwasm/tree/main/packages/vm

**Comment by jimjbrettj** [comment]
This is no longer relevant as we have replaced wasmer with wazero in our codebase
