### ISSUE TITLE
Support `BitVec` in scale

### ISSUE THREAD

**Issue by kanishkatn** [ChainSafe/gossamer#3248]
## Issue summary

Extend `pkg/scale` to support [BitVec](https://github.com/paritytech/parity-scale-codec/blob/master/src/bit_vec.rs).  

## Tasks

- [x] A basic implementation for ParachainHost runtime exports #3253
- [ ] Support `BitOrder` https://github.com/ChainSafe/gossamer/pull/3253#discussion_r1192257419
- [ ] https://github.com/ChainSafe/gossamer/pull/3253#discussion_r1196935277

## Other information and links
-  #3241

**Comment by axaysagathiya** [comment]
According to my observation and discussion with @EclesioMeloJunior, we need only the LSB0 ordering that we already have.
So, I guess this issue is not relevant anymore.
