### ISSUE TITLE
BABE: added reusing last epoch data in case of skipped epochs

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#3430]
## Issue summary

- Update to BABE spec to reuse last epoch data in case of skipped epochs

## Other information and links

- https://github.com/w3f/polkadot-spec/pull/685 (w3f spec update)
- https://github.com/w3f/polkadot-spec/issues/681 (issue describing the problem)
- https://github.com/paritytech/substrate/pull/11727 (substrate update)

## Tasks related

- [x] https://github.com/ChainSafe/gossamer/pull/3796
- [x] https://github.com/ChainSafe/gossamer/issues/3795
- [x] https://github.com/ChainSafe/gossamer/issues/3866
- [x] https://github.com/ChainSafe/gossamer/issues/3915
- [x] https://github.com/ChainSafe/gossamer/issues/3881

**Comment by EclesioMeloJunior** [comment]
Openned PR https://github.com/ChainSafe/gossamer/pull/3841 that introduces the new approach to retrieve the very first slot
