### ISSUE TITLE
CLI improvements

### ISSUE THREAD

**Issue by kanishkatn** [ChainSafe/gossamer#3590]
## Task summary

This serves as an epic for CLI improvements.

Currently, we only support the development flow in the cli and it doesn't have a production flow wherein we need to support account generation, custom accounts etc.

- [ ] Add a flag to differentiate between development and production use within the CLI.
- [ ] Creating separate configuration settings for development and production environments.
- [ ] Auto generate account if not specified #3255 

Other tasks:
- [ ] Create a data directory for the databases #3211 
- [ ] Separate config for sync service #3240 

## Other information and links
- #3163
- #3173
- https://github.com/ChainSafe/gossamer/issues/3255#issuecomment-1816906742

**Comment by timwu20** [comment]
@timwu20 investigate if we need any issues created relating to Full Node MVP
