### ISSUE TITLE
Implement database access functions for availability store subsystem

### ISSUE THREAD

**Issue by edwardmack** [ChainSafe/gossamer#3628]
## Task summary

Implement functions that handle loading, writing and deleting from availability store database tables
- [ ] loadAvailableData to read from available table
- [ ] writeAvailableData to add/edit data in available table
- [ ] deleteAvailableData to delete records from the available table
- [ ] loadChunk to read from chunk table
- [ ] writeChunk to add/edit data in chunk table
- [ ] deleteChunk to delete records from chunk table
- [ ] loadMeta to read from meta table
- [ ] writeMeta to add/edit data in meta table
- [ ] deleteMeta to delete records from meta table
- [ ] deleteUnfinalizedHeight to remove unfinalized height record from meta table
- [ ] deleteUnfinalizedInclusion to remove unfinalized inclusion record from meta table
- [ ] writePruningKey to add pruning key record to prune_by_time table
- [ ] deletePruningKey to delete pruning key record from prune_by_time table
- [ ] writeUnfinalizedBlockContains to add/edit unfinalized block contains record to prune_by_time table

## Specification reference

- Replicate functionality for Polkadot node: https://github.com/paritytech/polkadot-sdk/blob/15a34838819f09f3bcfb3c05c08fb53934d8efc4/polkadot/node/core/av-store/src/lib.rs#L180

## Other information and links

- As described in Implementers' Guide: https://paritytech.github.io/polkadot-sdk/book/node/utility/availability-store.html#database-schema

**Comment by edwardmack** [comment]
closed when PR #3640 was merged.
