### ISSUE TITLE
trie: Translate parity trie crate

### ISSUE THREAD

**Issue by dimartiro** [ChainSafe/gossamer#3732]
# Description
We need change our current trie implementation and start using parity's implementation.

This will bring us a lot of benefits, some of them are:

- Nodes and values cache support
- Nodes lazy loading
- Improve memory usage
- More flexibility for future changes

## Todo

In order to do this we have to translate the following components:

- [x] [HashDB](https://github.com/paritytech/trie/blob/master/hash-db/src/lib.rs) trait 
- [x] [MemoryDB](https://github.com/paritytech/trie/blob/master/memory-db/src/lib.rs)
- [ ] [TrieDB](https://github.com/paritytech/trie/blob/master/trie-db/src/triedb.rs)
   - [x] [Lookup](https://github.com/paritytech/trie/blob/master/trie-db/src/lookup.rs)
   - [x] [Recorder](https://github.com/paritytech/trie/blob/master/trie-db/src/recorder.rs)
- [x] [Node enums](https://github.com/paritytech/trie/blob/master/trie-db/src/node.rs)
- [x] [NodeCodec](https://github.com/paritytech/trie/blob/master/trie-db/src/node_codec.rs)
- [x] [NodePlan](https://github.com/paritytech/trie/blob/542829a8195c12b67eef05e9020ec7a6d9313c3f/trie-db/src/node.rs#L499-L580)
- [ ] [Proof generation](https://github.com/paritytech/trie/blob/master/trie-db/src/proof/generate.rs)
- [ ] [Proof verification](https://github.com/paritytech/trie/blob/master/trie-db/src/proof/verify.rs)
- [ ] Testing
  - [ ] Test Support
     - [ ] [KeccakHasher](https://github.com/paritytech/trie/blob/master/test-support/keccak-hasher/src/lib.rs)
     - [ ] [Substrate reference-trie](https://github.com/paritytech/trie/blob/master/test-support/reference-trie/src/substrate.rs)

**Comment by dimartiro** [comment]
We are not going to translate but we are going to get some inspiration from them. So I'll close this issue
