### ISSUE TITLE
Sync with Paseo: Fix bugs related to tip sync

### ISSUE THREAD

**Issue by jimjbrettj** [ChainSafe/gossamer#3789]
## Issue summary

- [ ] Sometimes when in tip sync mode the node will crash with an index out of bounds error (see 1)
- [x] On startup, sometimes the node will not begin and then when it's stopped it panics (see 2)
- [ ] Related to the above issue, sometimes before the spam logs we get errors from peerset (see 3)
- [ ] Sometimes we get to tip sync and don't progress (see 4)
- [ ] We also get this error every so often (see 5)

1)
 ![image](https://github.com/ChainSafe/gossamer/assets/40345116/d33599e6-9b94-4135-b9d4-d5a4c6409357)

2) 
![image](https://github.com/ChainSafe/gossamer/assets/40345116/63882e2f-da83-4deb-9b4d-092cb110b1e0)

3) 
![image](https://github.com/ChainSafe/gossamer/assets/40345116/87f59f38-6d14-4dc5-8832-33d450fd24b6)

4) 
![image](https://github.com/ChainSafe/gossamer/assets/40345116/794b89d3-2be7-40b7-a2ea-1c4144cd7224)

5)
![image](https://github.com/ChainSafe/gossamer/assets/40345116/da9e59fd-79c8-452b-93d3-d9d9d91d0bbf)
