### ISSUE TITLE
 Implement collator protocol's collator side 

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3824]
## Issue summary

This is not necessary to become an authoring node, but for becoming a collator node.
This might be a low priority, but having some of the things from this subsystem implemented helps us in the test when we want to spin up a collator node.

## Sub Issues

- [x] A skeleton PR, that introduces this subsystem, registers it, has processMessage, implements SubSystem interface
- [ ] handle collation seconded message
- [ ] handle distribute collation message
- [ ] handle network bridge update messages 
- [ ] handle active leaves update signal
- [ ] handle block finalized signal
- [ ] support v2 and v3 of the protocol

## Other information and links

- https://paritytech.github.io/polkadot-sdk/book/node/collators/index.html
- https://github.com/paritytech/polkadot-sdk/blob/aa68ea58f389c2aa4eefab4bf7bc7b787dd56580/polkadot/node/network/collator-protocol/src/collator_side/
