### ISSUE TITLE
Common network bridge for parachain subsystems

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#3830]
## Task summary

Finally I have given up and decide to have a network bridge. It is the bridge between overseer and the network.

- It makes things way easier to understand and implement (because that's what polkadot sdk has)
- There is a lot of common code that network bridge has. Without it, we would have to have same code twice, once in collation and once in validation protocol
- Along with protocol messages, nodes also share view updates with each other over the network. This is also something that becomes easier with network bridge.

## Sub Issues
Rust code base has used separate subsystem for receiver and sender side of network bridge and se

### Receiver side 
https://github.com/paritytech/polkadot-sdk/blob/665e3654ceca5a34e8ada66a9805fa7b76fc9ebb/polkadot/node/network/bridge/src/rx
- [x]  (dot/parachain): create skeleton for receiver side of network bridge #3860 
- [x]  (dot/parachain): process network events for receiver side of network bridge #3863 
- [x] (dot/parachain): process overseer signals for network bridge #3861 
- [x]  (dot/parachain): Handle network bridge messages (NetworkBridgeRxMessage type) https://github.com/ChainSafe/gossamer/issues/3862
- [x]  (dot/parachain): handle view update message for receiver side of the network bridge #3864 

### Sender side
- [x] https://github.com/ChainSafe/gossamer/issues/3858
- [x] https://github.com/ChainSafe/gossamer/issues/3859

## Specification reference

- 

## Other information and links

- https://github.com/paritytech/polkadot-sdk/blob/aa68ea58f389c2aa4eefab4bf7bc7b787dd56580/polkadot/node/network/bridge/

**Comment by kishansagathiya** [comment]
All the sub issues have been closed, so can safely close this.
