### ISSUE TITLE
Candidate backing Write full integration tests

### ISSUE THREAD

**Issue by axaysagathiya** [ChainSafe/gossamer#4094]
## Issue summary

These are tests that are not so important to implement now. We can write these tests later. 

- [ ] https://github.com/ChainSafe/gossamer/issues/4011
- [ ] https://github.com/ChainSafe/gossamer/issues/4012
- [ ] https://github.com/ChainSafe/gossamer/issues/4010

## Other information and links

-
