### ISSUE TITLE
feat(statement-distribution) handle `NetworkBridgeUpdate` signal

### ISSUE THREAD

**Issue by kishansagathiya** [ChainSafe/gossamer#4172]
## Issue summary

This signal comes from network bridge with informations about peers connected, peers disconnected, grid topology update, new message from a peer and other messages.

- [ ] Implement `handle_network_update` https://github.com/paritytech/polkadot-sdk/blob/74ec1ee226ace087748f38dfeffc869cd5534ac8/polkadot/node/network/statement-distribution/src/v2/mod.rs#L428C21-L428C42

### Support Network Bridge Events (v2)
- [ ] PeerConnected
- [ ] PeerDisconnected
- [ ] NewGossipTopology
- [ ] PeerMessage 
  - [ ] `handle_incoming_statement` https://github.com/ChainSafe/gossamer/issues/4392 -> separated PR
  - [ ] `handle_incoming_manifest_common` https://github.com/ChainSafe/gossamer/issues/4393 -> separated PR
  - [ ] `handle_incoming_acknowledgement` https://github.com/ChainSafe/gossamer/issues/4395 -> separated PR
- [ ] PeerViewChange
- [ ] UpdatedAuthorityIds

## Other information and links

- https://github.com/paritytech/polkadot-sdk/blob/aaf0443591b134a0da217d575161872796e75059/polkadot/node/network/statement-distribution/src/lib.rs#L377
