### ISSUE TITLE
feat(dot/sync): Improve worker pool

### ISSUE THREAD

**Issue by EclesioMeloJunior** [ChainSafe/gossamer#4198]
## Task summary

- Currently, our sync worker pool contains few pitfals related to how we treat and use channels and goroutines
- We need a better implementation that should be generic and robust enough to handle retries logic and maybe more broader use cases.

Few points that needs to be addressed
- [ ] worker pool should handle tasks async or should it resolve all batch of tasks and then return?
- [ ] setup a max amount of failures in the pool then we can just ignore the worker (forever? or during a timeout)
- [ ] worker pool should be able to resolve if there's no workers or all workers failed to resolve the tasks

### Proposed interface
by @timwu20 
```
package pools

type Task any
type TaskID string
type TaskResult struct {
	ID         TaskID
	NumRetries uint // if we care
}
type Result any
type BatchStatus struct {
	Failed  map[TaskID]TaskResult
	Success map[TaskID]TaskResult
}
type WorkerPool interface {
	Results() chan Result
	SubmitBatch(tasks ...Task) (batchID string)
	GetBatch(batchID string) BatchStatus
	Shutdown() error // we impl graceful shutdown
}

// Retry, numWorkers, timeouts, etc.
type WorkerPoolOptions any

func NewWorkerPool(opts ...WorkerPoolOptions) WorkerPool {
	panic("unimpl")
}
```

**Comment by haikoschol** [comment]
This turned out to be less straightforward than expected and more of an investigation than a clear improvement. None of the tried approaches were better (e.g. faster) than the current implementation. Below is a description of my findings while working on this.

## Issues with the Current Implementation

*None of the below issues are critical. The current implementation works, at least until we hit known, unrelated issues ([storage root mismatch](https://github.com/ChainSafe/gossamer/issues/4182), [grandpa justification verification](https://github.com/ChainSafe/gossamer/issues/4190)).*

1. Running out of peers during execution of a batch.

Peers connect and disconnect while a batch is being processed. They are added to the worker pool when a block announce handshake is received from them and removed if sending a request to them results in an error. Before a batch is executed, the pool allocates as many peers as there are tasks for the batch or fewer, if not enough peers are available.
When a request succeeds, the peer is added back to the allocated channel for the batch. If it fails, the peer is not added back. Tasks are retried until they succeed or the pool runs out of peers.

2. Waiting until all blocks in the batch have been retrieved before importing them.

This seems non-optimal in terms of performance: CPU/memory-bound work of importing blocks could be performed concurrently with network-bound work of requesting blocks. In practice, it might be more beneficial to process ordered fragments without gaps after the whole batch has completed (see details under Current State on the Feature Branch). Although that is not guaranteed since tasks can be given up on (see 1.)

3. [Complex retry logic](https://github.com/ChainSafe/gossamer/pull/4114#discussion_r1744732523)

## Issues with Proposed API

The API proposed in [the GH issue](https://github.com/ChainSafe/gossamer/issues/4198) includes keeping track of a batches status for which an ID is returned from `SubmitBatch()`. When I adapted the `SyncService` to use this API, I found that the feature was not needed. Instead, I fed the task results into `SyncService.Process()` via the channel returned by `WorkerPool.Results()`. At the same time, having this struct in the pool created a lot of lock contention and issues with deadlocks during regression tests. In short, my changes were worse than the current implementation.

## Current State on the Feature Branch

After watching [this great talk on concurrency patterns in Go](https://www.youtube.com/watch?v=5zXAHh5tJqQ), I tried to simplify and apply the ideas from it to the worker pool. Mostly to share as much state as possible via communicating. I simplified the worker pool API, removing `GetBatch() BatchStatus` and made the invariants stricter: The caller must consume all results of the current batch before submitting a new one. Task are retried indefinitely. Additionally, peers are managed in a channel. One downside of this over a `map` is that there could be duplicates. In the worst case, the channel only contains one peer ID.
This let to sync on Paseo stalling with one task being retried over and over, always receiving an empty message. What makes this even more annoying is that the block(s) in that request had already arrived through some other requests so it would have been fine to give up on the permafailing one. In other words, this approach is worse than the current implementation as well.

## General Issue with Increased Concurrency

Having the `Strategy` consume task results as they arrive instead of waiting for the whole batch has one unexpected downside. Because the blocks from the batch are not complete and in order, the `Strategy` adds additional requests to fill in the gaps. During regression tests on my feature branch I noticed a lot of "ancestor search" log messages whereas there are none with the current implementation.

## Options for How to Proceed

1. Close the PR (and maybe the issue as `wontfix`) and just stick with the current implementation.

2. Make somewhat invasive changes to `Strategy` and probably `SyncService`, such that
    - After `N` retries, the worker pool communicates to `SyncService` that one or more requests have still not succeeded.
    - `SyncService` asks `Strategy` whether the request still needs to be fulfilled in order to make progress (or decides itself).
    - If yes, `SyncService` tells worker pool to keep trying.

This requires to somehow avoid stalling sync while one (or more) remaining tasks get retried over and over. Maybe the number of retries needs to be dialed in with regression tests?

**Given that we have more than enough work with higher priority, we decided to go with option 1. We can always reopen this issue if we want to optimize full sync speed later.**
